### ISSUE TITLE
wp_get_attachment_image_srcset() returns false

### ISSUE THREAD

**Issue by katerlouis** [cloudinary/cloudinary_wordpress#359]
I created a free plan account on Cloudinary and connected it to our Wordpress 5.6.1 installation with the Cloudinary Wordpress plugin v2. 

After syncing all assets to Cloudinary `wp_get_attachment_image_srcset($attachmentId)` is `false`. I then activated "Enable responsive images" under "Media settings -> Image breakpoints" and resynced all images. But the function is still returning `false`.

I double checked that the correct Ids get passed to the function. 

Do I have to use another function to get the `srcset`?

**Comment by cloudinaraz** [comment]
Hey @katerlouis,

Sorry for the delay in response.

You are correct that the `wp_get_attachment_image_srcset($attachmentId)` doesn't currently function normally for assets synced with Cloudinary. 
We have an internal ticket to analyze and address this behavior in the near future. 

Meanwhile, can you please share with us the use case that requires you to make use of this WP function to retrieve the srcset of certain images instead of letting the plugin automatically generate it for you when you have the responsive breakpoints option enabled in your plugin's global transformations page?

**Comment by cloudinaraz** [comment]
@katerlouis I haven't heard back from you yet, but if adding the images using `wp_get_attachment_image()` is an option, then this is the way to go. Using this, it will properly generate the `src` and `srcset` parameters — that is, using Cloudinary URLs.
