### ISSUE TITLE
Skipping SVGs from optimizations

### ISSUE THREAD

**Issue by ghost** [cloudinary/cloudinary_wordpress#447]
Hello,

I am trying to determine the best way to skip `.svg` files from being optimized. I see from this [filter](http://cloudinary.github.io/cloudinary_wordpress/cloudinary_convert_media_types.html) that `.svg` files initially get converted to `.png`. But if I use that filter to remove `.svg` from the array, they still are served from Cloudinary but if you inspect the network tab they are being served as `.webp`.

The only reliable solution I have found is to just set the image format option in the plugin to "Not set", but that is overkill when you only need to prevent one file format from being converted.

Here is an example of the filter I am using, maybe I am just using it wrong:

```php
function filterCloudinaryConversionTypes($base_types) {
    unset($base_types['svg']);
    return $base_types;
}

add_filter('cloudinary_convert_media_types', 'filterCloudinaryConversionTypes');
```

or even

```php
function filterCloudinaryConversionTypes() {
    $base_types = array(
        'psd'  => 'jpg',
        'ai'   => 'jpg',
        'eps'  => 'jpg',
        'ps'   => 'jpg',
        'ept'  => 'jpg',
        'eps3' => 'jpg',
        'indd' => 'jpg',
        'webp' => 'gif',
        'bmp'  => 'jpg',
        'flif' => 'jpg',
        'gltf' => 'jpg',
        'heif' => 'jpg',
        'heic' => 'jpg',
        'ico'  => 'png',
        'tga'  => 'jpg',
        'tiff' => 'jpg',
        'tif'  => 'jpg',
    );

    return $base_types;
}

add_filter('cloudinary_convert_media_types', 'filterCloudinaryConversionTypes');
```

Using the individual level transformations here is not feasible as that is not something that we would want our clients to handle on their own. Thanks!

**Comment by Vdeub-cloudinary** [comment]
Hi @apersky, 

SVGs are not supported by WordPress by default, that's the reason why we convert them to a `png`. When images are getting optimized using `f_auto` and `q_auto`, it is usual to get a `webp` if you are on Chrome. 

The best way to not applied transformations to SVGs would be to not sync them with Cloudinary hence you will need to set your sync process to `Manual Sync` and only push to Cloudinary the files you need.

**Comment by apersky** [comment]
Hi @Vdeub-cloudinary thanks for the reply.

I am aware that WP does not natively support SVG. But when clients have SVG logos and icons, that's what we need to use. Your plugin converting SVG to PNG is a clear indicator that you are aware that SVGs will end up in the Media Library regardless of if WordPress has native support or not.

However, it is still not feasible to expect a client (or anybody really) to manually sync all assets except SVGs from the Media Library, especially when Cloudinary is added after the fact. Some of our client sites easily have hundreds and hundreds of assets. Manual sync is just not realistic here.

So, back to my original question. Am I using this filter incorrectly? I understand why you are converting SVG to PNG, but I also understand that the point of a filter is so that we the developers can alter this behavior, which is what I am trying to do. 

Please advise on the proper use of this filter. Thanks!

**Comment by victorli-cloudinary** [comment]
Hi @apersky 

Loic is out of office currently so I'll chime in here.

Thanks for these updates, I've forwarded your questions directly to the dev team and we will respond to you once they have updates to share with you.

**Comment by apersky** [comment]
Hi @victorli-cloudinary,

Thank you. Awaiting your reply. Have a good weekend!

**Comment by Vdeub-cloudinary** [comment]
Closing as `3.0.0` supports now SVG without optimization.
