### ISSUE TITLE
Bug Report: Cloudinary Version 3.0.2 - cloudinary.openMediaLibrary is not a function

### ISSUE THREAD

**Issue by danigonlinea** [cloudinary/cloudinary_wordpress#720]
Hi Cloudinary team,

Just wanted to report an issue I had on my website with the latest version released. 

Steps to reproduce the bug:

- Path: `Products` > `Attributes` > `Edit any existing attribute` > `Upload/Add Image` > `Select Cloudinary Tab` 
- State: I have infinite loading and a error on dev console `cloudinary.openMediaLibrary is not a function`

 Debugging it hightlights the next line so you can have easily context:

![2022-03-28 22 30 58](https://user-images.githubusercontent.com/1208620/160481924-24ae101c-17c0-4162-b9e1-f3489a40c64f.jpg)
 
 PD: I have rolled back to a stable version `2.7.6` which is working as expected so I'm good about when it could be fixed.
 
Thanks in advance for such a great and useful plugin!

**Comment by Vdeub-cloudinary** [comment]
Hi @danigonlinea - would you mind opening a ticket to support@cloudinary.com with a system report as documented [here](https://support.cloudinary.com/hc/en-us/articles/360022260599-How-to-generate-a-system-report-on-the-WordPress-plugin-)? I believe you need a specific plugin to add attributes to Products on WooCommerce so I just want to make sure I have the same plugin in order to reproduce. 

Also, is it the only place you are having an issue with Cloudinary when uploading an image this way? Does it work if you enable the `Cloudinary DAM` extension as documented [here](https://support.cloudinary.com/hc/en-us/articles/360017521280-WordPress-Plugin#dam_extension)?

Thanks!

**Comment by danigonlinea** [comment]
Thank you for your answer, 

I need to rush with something this week but when I came to normal again, I will try to upgrade again to the latest version.

Actually, that was the only place that the plugin was throwing me this error, the rest was working fine. probably as you suggested, enabling this extension that I wasn't aware of, could fix the problem.

Give me some time to figure it out and if the problem persists, I will send a ticket to the support as you suggested.

Thank you so much ;-)

**Comment by Vdeub-cloudinary** [comment]
@danigonlinea sure no problem :) please reach out to support@cloudinary.com if you still encounter the issue after your tests.

**Comment by Vdeub-cloudinary** [comment]
@danigonlinea - no need for a ticket, this should be fixed in the next version `3.0.3` - I'll get back to you when we have an ETA for this.
