### ISSUE TITLE
f_mp4 returns error

### ISSUE THREAD

**Issue by dafitime** [cloudinary/cloudinary_wordpress#89]
Support issued ticket, but I am sending formal ticket here.

When adding f_mp4 to the image transformation for global, it returns "Invalid transformations or erro loading preview."

**Comment by idobarnoam** [comment]
Hi @dafitime 

When applying f_mp4 to a resource it would mean that the resource would be transcoded to an mp4.

On images its not possible to do that, which means its an incorrect terraformation, which is why you are getting this error message when applying that global transformation to images.

Note that the plugin has a "video settings" tab which allows global transformation for videos (and audio resources). Applying `f_mp4` as a global transformation there would work.

Let me know if that makes sense.

**Comment by dafitime** [comment]
The global transformation for images as far as I know, would inject between the url links via wp_add_inline_script. I'm still learning php coding, but I do see on the plugin that it will append the Cloudinary Transformation in the global transformation box.

`https://res.cloudinary.com/dievmtuck/image/upload/v1590214137/tenor-1.gif`
which is the example gif.
However, adding f_mp4 would result in the video transformation without changing the extension.
`https://res.cloudinary.com/dievmtuck/image/upload/v1590214137/f_mp4/tenor-1.gif`

I was looking into writing the code to inject /f_mp4/ for all of my dynamic links, but it's a bit beyond my coding capabilities atm.

**Comment by shirlymanor** [comment]
It's an issue on our end, when using a gif it's unique because it uploaded as an image but can use as a video (when adding f_mp4) and in WordPress, we are serving it in an image tag. which generated an error.

**Comment by pereirinha** [comment]
Given the last comment, I'm closing the issue.
